class AdvitoError(Exception):
    pass

class LoginError(AdvitoError):
    pass
